name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up nodejs v15
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install

      - name: Execute linter
        run: npm run build
